mili:
  version: 3.6.0
template:
  repository: 'https://github.com/Val-istar-Guo/component-template.git'
  version: 2.6.5
answers:
  ci: true
  standardVersion: true
  lint: true
  lock: false
  package: NodeJS
